########################################################
# EE232E SPRING 2017 PROJECT 2 
# PROBLEM 3
# AUTHORS: SILEI MA, HONGYANG LI, NIEN-JEN CHENG
########################################################

library(igraph)

##### Problem 3 #####
# Read actor network (act_directed_net.txt is generated by Problem 1-2.py)
fileDir = "/Users/pseu/Desktop/act_directed_net.txt"
# Generate graph
actor_graph = read.graph(file = fileDir , format = "ncol", directed = T)
pr = page.rank(actor_graph, directed = TRUE, damping = 0.85)
pr_sort = sort(pr$vector, decreasing = TRUE, index.return = TRUE)
print(pr_sort$x[1:10])