########################################################
# EE232E SPRING 2017 PROJECT 2 
# PROBLEM 5-6
# AUTHORS: SILEI MA, HONGYANG LI, NIEN-JEN CHENG
########################################################

library(igraph) 

########################################################
##### Problem 5 #####
# Read movie network (mov_undirected_net.txt is generated by Problem 4.py)
movie_graph = read.graph("C:/Users/pseu/Desktop/mov_undirected_net.txt",format="ncol",directed=FALSE)

# Fast Greedy Algorithm
movie_comm<-fastgreedy.community(movie_graph)
sizes(movie_comm)
modularity(movie_comm)
#plot(movie_comm, movie_graph, vertex.label=NA)

# Read genre network (mov_gen_list.txt is generated by Problem 5.py)
genre_list <- file("C:/Users/pseu/Desktop/mov_gen_list.txt",open = "r")
gen_mov <- readLines(genre_list)
close(genre_list)

# Assign genre attribute to each node
V(movie_graph)$genre = gen_mov[as.numeric(V(movie_graph)$name)]

# Tag communtiy with genre appears more than 20%
for(i in 1:length(movie_comm)){
  comm_genre = V(movie_graph)[which(movie_comm$membership==i)]$genre
  genre_type = unique(comm_genre)
  comm_tag=numeric(0)
  for(genre in genre_type){
    if(length(which(comm_genre==genre))>=length(comm_genre)*0.2 && genre!="Null"){
      comm_tag<-c(comm_tag,genre)
    }
  }
  cat(i,"\t",comm_tag,"\n")
}



########################################################
##### Problem 6 #####
# Add the three movies (Index found in mov_list.txt generated by Problem 4.py)
MovieID = c(894354,779751,763763)
for (id in MovieID){
  movie_node = which(V(movie_graph)$name == id)
  
  # Find five nearest neighbors of the movie
  neighbor_nodes = neighbors(movie_graph, movie_node)
  neighbor_weight = numeric(0)
  for (neighbor_node in neighbor_nodes){
    weight = E(movie_graph,P=c(movie_node,neighbor_node))$weight
    neighbor_weight = c(neighbor_weight,weight)
  }
  neighbor_weight_sorted = sort(neighbor_weight,decreasing =T,index.return =T)
  neighbor_sel_idx = neighbor_nodes[neighbor_weight_sorted$ix[1:5]]
  neighbor_sel_id = V(movie_graph)[neighbor_sel_idx]
  
  cat("Added Movie: ",id,"\n")
  cat("Neighbor MovieID: ",V(movie_graph)[neighbor_sel_id]$name,"\n")
  cat("Neighbor Community: ",movie_comm$membership[neighbor_sel_id],"\n")
}

