########################################################
# EE232E SPRING 2017 PROJECT 2 
# PROBLEM 9
# AUTHORS: SILEI MA, HONGYANG LI, NIEN-JEN CHENG
########################################################

library(igraph)

##### Problem 9 #####

# Construct Bipartite Graph (act_mov_net.txt is generated by Problem 9.py)
act_mov = read.graph("C:/Users/pseu/Desktop/act_mov_net.txt",format="ncol",directed=FALSE)
colnames(act_mov) = c("Actors", "Movies")
bipartite.actor.movie = graph.data.frame(act_mov, directed = FALSE)

for (i in 1:length(unique.actors.edge)) {
  actors.node.ratings = c(actors.node.ratings, mean(map.ratings.to.movies[neighbors(bipartite.actor.movie, unique.actors.edge[i])$name,]))
}

